### ISSUE TITLE
Customer UI: Starting page

### ISSUE THREAD

**Issue by konnerRG** [NANABAN-RAMEN-project/953262-953234-project#1]
This will be the introduction page for the ordering website. It is a ramen shop, with red and white as their signature color scheme. The website will be simple and modern, while still keeping some traditional Japanese styling. 

*Requirements:
- Logo shown front and center of the page
- A button to go to the "Select Table" page
- A pseudo-navbar on top of the page
- A footer showing the trademark, shop's address and social icons

**Comment by Panadon-s** [comment]
### Design:

- Add Logo at the top and center of the page
- Add "Select Table" button below the center logo
- Add navbar on the top of the page

![image](https://user-images.githubusercontent.com/77398559/157242854-a7c03286-ff5d-4dce-ab84-91fab5cb406e.png)

**Comment by Panadon-s** [comment]
### Design: 

- Add footer to show shop's address, social icon and trademark

![image](https://user-images.githubusercontent.com/77398559/157243073-0a073e7b-62ab-4ca7-a7ac-563662505b46.png)

**Comment by konnerRG** [comment]
### **Development:**
- c61e98c - created index.js & npm extensions 
- dbf6ed3 - Created homepage and included css files

![image](https://user-images.githubusercontent.com/77325108/158055722-e31f8681-3f5d-48d3-999c-6e5e2a64ed70.png)
