### ISSUE TITLE
Customer UI: Select Table

### ISSUE THREAD

**Issue by konnerRG** [NANABAN-RAMEN-project/953262-953234-project#2]
This page is where the customers will choose where they are currently sitting. This page will show what table is available to prevent human error.

*Requirements:
- An indication that the seat is available/taken
- A diagram of how many seats there are
- A label on the navbar to remind the user what page they are at

**Comment by Panadon-s** [comment]
### Design: 

- Use diagram to represent as a tables
- Use color green/red to indicate if the tables are vacant or not [green means vacant / red means taken]
- Label "Select Table" at the top of the page to remind user where they're at

![image](https://user-images.githubusercontent.com/77398559/157245069-9e9e85ec-2e92-4a6f-b412-3d0aba4b058c.png)

**Comment by konnerRG** [comment]
### **Development:**

- 8cc7111 - insert select-table.ejs

![image](https://user-images.githubusercontent.com/77325108/158059838-f59872d1-1490-4af2-9f83-4a7ee19b217d.png)
