### ISSUE TITLE
Customer UI: Menu & Order 

### ISSUE THREAD

**Issue by konnerRG** [NANABAN-RAMEN-project/953262-953234-project#3]
This page contains the menu and it's description. This is where the customer will choose their menu and quantity. 

*Requirements:
- Menu contains 3 types; appetizers, main dish and beverage on the left side
- The menu is displayed in the middle of the screen, each menu must contain price and can choose quantity
- The right side contains the list of ordered items, and a pay button below.
- Optional->customer can ask for custom requests for the order

**Comment by Panadon-s** [comment]
### Design

- Divide design into 3 sections left, center and left
- Left section design to hold menu types such as appetizer, main dish and beverage
- Center section hold collection of menus categorize by menu types
- Right section list all of the ordered items and order button
- *Also add label "Order" as reminder on top of the page

![image](https://user-images.githubusercontent.com/77398559/157251944-e2cf8c1c-b2a0-42e0-9255-fa0ea69500cb.png)

**Comment by konnerRG** [comment]
### **Development:**
- b851111 - add order-online-page and model files

![image](https://user-images.githubusercontent.com/77325108/158071583-d84a022d-1b13-4427-adb4-282644650f58.png)

Can add and delete items in table:

![image](https://user-images.githubusercontent.com/77325108/158071664-6d11e5cd-289a-49b6-816b-7cd2ffbd73fb.png)
