### ISSUE TITLE
Customer UI: Order Status & Checkout

### ISSUE THREAD

**Issue by konnerRG** [NANABAN-RAMEN-project/953262-953234-project#4]
This is where the customer will be able to check the progress of each dish. The customer can cancel the order as long as it is still in "queue" status. The customer can also click to checkout and pay or go back and order again.

*Requirements:
- A table containing the name of menu, quantity, price and status
- The table contains a button for the customer to cancel order
- There are 2 buttons below the page, 1. back to menu 2. checkout
- The checkout page will display the list again and the total price
- Customer can cancel to order more, or pay and it will redirect to the starting page

**Comment by Panadon-s** [comment]
### Design:

- A table contain the menu, quantity, price and status
- Add button to cancel order
- Add back to menu button and checkout button to the design
- Add label "Order Status" as a remider

![image](https://user-images.githubusercontent.com/77398559/157253763-06b5407e-5f65-44d3-b651-1bd4387622d5.png)

**Comment by Panadon-s** [comment]
### Design:

- Add checkout page to list all ordered menu and total price
- Add pay and cancel button
- Add Label "Checkout"

![image](https://user-images.githubusercontent.com/77398559/157254402-39a5f688-603c-4e41-9b47-8f138f497835.png)

**Comment by konnerRG** [comment]
### **Development:**

- deb2485 - add order-status page

![image](https://user-images.githubusercontent.com/77325108/158158168-7f7d2246-2ae8-45f7-908a-0b6dcc5d0c35.png)
