### ISSUE TITLE
Kitchen UI: Login Page 

### ISSUE THREAD

**Issue by konnerRG** [NANABAN-RAMEN-project/953262-953234-project#5]
This is where the kitchen staffs gain access to the customer's orders. This page is where the kitchen staff needs authentication to be able to login to the site.

*Requirements:
- Black and white theme
- Authentication

**Comment by Panadon-s** [comment]
### Design:

- Shift the color design from customer UI to black and white theme
- Authentication by entering username and password in the box
- Add label "Kitchen Staff"

![image](https://user-images.githubusercontent.com/77398559/157254957-9c06e787-e307-4293-847e-b809ca1940b8.png)

**Comment by konnerRG** [comment]
### **Development:**

- 413cbc9 - add kitchen-login page

![image](https://user-images.githubusercontent.com/77325108/158159427-91c165ba-e96d-49d1-be37-d8e28f155c27.png)
