### ISSUE TITLE
Kitchen UI: Order List

### ISSUE THREAD

**Issue by konnerRG** [NANABAN-RAMEN-project/953262-953234-project#6]
This page is where the staffs can look at the orders and can state the food's progression (Queue/Cook/Served)

*Requirements:
- This page must link to the customer's order
- The staffs can change the progression with buttons
- can show the state that the dish is canceled

**Comment by Panadon-s** [comment]
### Design:

- Table that shows customer's order
- Add progression button as cooked and served

![image](https://user-images.githubusercontent.com/77398559/157255497-7fb4429a-2138-4892-9f25-988b32fd78c1.png)

**Comment by konnerRG** [comment]
### **Development:**

- 450dcbc - add kitchen-order-list page

![image](https://user-images.githubusercontent.com/77325108/158162710-08cf53c5-d19b-4341-97d6-abb1274812c7.png)
